### ISSUE TITLE
better (i dont want to make a pr)

### ISSUE THREAD

**Issue by imvast** [xKiian/xKiian#2]
<p align="center">
  <img height="25" src="https://api.visitorbadge.io/api/VisitorHit?user=xkiian&countColor=%234a12ba" alt="Profile Views"/>
  <img height="25" src="https://img.shields.io/github/followers/xkiian?color=4a12ba&style=for-the-badge&logo=github&label=Follow" alt="Followers"/>
  <img height="25" src="https://img.shields.io/github/stars/xkiian?color=4a12ba&style=for-the-badge&logo=github&label=Stars" alt="Stars"/>
</p>

```python
from abc import ABCMeta, abstractstaticmethod


class IxKian(metaclass=ABCMeta):
    @abstractstaticmethod
    def contact():
        return ["discord", "telegram"]

    @abstractstaticmethod
    def life():
        return self.coding()

    @abstractstaticmethod
    def coding():
        pass


class Attributes(IxKian):
    @staticmethod
    def contact() -> tuple:
        discord: str = ".xkian"
        telegram: str = "xKian"

        return discord, telegram

    @staticmethod
    def life() -> tuple:
        return ("German", "English")

    @staticmethod
    def coding() -> tuple:
        text_editor = "VSCode"
        specialities = [
            "Reverse Engineering", 
            "Website Automation",
            "Touching Kids"
        ]
        langs = {
            "pro": "python", 
            "intermediate": ["go", "c++"], 
            "learning": "js"
        }
        return langs, specialities, text_editor
```
<div style="display: flex; justify-content: center;">
    <img src="https://github-profile-summary-cards.vercel.app/api/cards/stats?username=xkiian&theme=tokyonight" width="33%">
    <img src="https://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=xkiian&theme=tokyonight" width="33%">
    <img src="https://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=xkiian&theme=tokyonight&utcOffset=1" width="33%">
</div>

**Comment by xKiian** [comment]
no cuz the stats dont align properly on mobile
